VERILOG_FOLDER			= src/
VERILOG_MAIN_FILE		= $(VERILOG_FOLDER)Top.v
VERILOG_SOURCES			= $(shell find $(VERILOG_FOLDER) -name '*.v')

VERILATOR_FOLDER		= verilator/
VERILATOR_BUILD_FOLDER	= $(VERILATOR_FOLDER)build/
VERILATOR_MAKEFILE		= VTop.mk
VERILATOR_MAIN_FILE		= $(VERILATOR_FOLDER)main.cpp
VERILATOR_EXECUTABLE	= $(VERILATOR_BUILD_FOLDER)simulation
VERILATOR_TRACE_FILE	= trace.vcd

MAKE					= make
MAKE_FLAGS				= -C $(VERILATOR_BUILD_FOLDER) -j $(shell nproc) -f $(VERILATOR_MAKEFILE)

VERILATOR				= verilator
VERILATOR_FLAGS			= -I$(VERILOG_FOLDER) -Wall -cc $(VERILOG_MAIN_FILE) -Mdir $(VERILATOR_BUILD_FOLDER) --trace --exe $(shell realpath "$(VERILATOR_MAIN_FILE)") -o $(shell realpath "$(VERILATOR_EXECUTABLE)")

GTKWAVE					= gtkwave
GTKWAVE_CONFIG			= config.gtkw
GTKWAVE_FLAGS			= $(VERILATOR_TRACE_FILE) $(GTKWAVE_CONFIG)

clean:
	-@rm -r "$(VERILATOR_BUILD_FOLDER)" "$(VERILATOR_TRACE_FILE)" 2>/dev/null || true

build: clean $(VERILATOR_EXECUTABLE)

run: $(VERILATOR_EXECUTABLE)
	@./$(VERILATOR_EXECUTABLE)

$(VERILATOR_TRACE_FILE): run

trace: $(VERILATOR_TRACE_FILE)
	-@echo "Opening '$(VERILATOR_TRACE_FILE)' in GTKWave..."
	@$(GTKWAVE) $(GTKWAVE_FLAGS)

$(VERILATOR_EXECUTABLE): $(VERILOG_MAIN_FILE) $(VERILOG_SOURCES)
	-@echo "Verilating Verilog sources..."
	$(VERILATOR) $(VERILATOR_FLAGS)
	-@echo "Compiling '$(VERILATOR_EXECUTABLE)'..."
	$(MAKE) $(MAKE_FLAGS)